[project]
name = "hackathon-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.0.2",
    "langchain-google-genai>=3.0.0",
    "streamlit>=1.50.0",
]
